substitutions:
  _REGION: us-central1
  _SERVICE: rcv-api
  _AR_REPO: rcv-api
  _IMAGE: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/rcv-api:${SHORT_SHA}
  _ENVVARS: NODE_ENV=production,DB_ENGINE=postgres,PGHOST=10.168.0.3,PGPORT=5432,PGDATABASE=rcvdb,PGUSER=rcvapp,FORCE_ADMIN_RESET=0,CORS_ORIGIN=https://rcvhn.github.io
  _SECRETS: JWT_SECRET=JWT_SECRET:latest,PGPASSWORD=PGPASSWORD:latest
  _CONNECTOR: rcv-conn

steps:
- name: gcr.io/cloud-builders/docker
  dir: backend
  args: ['build','-t','${_IMAGE}','.']

- name: gcr.io/cloud-builders/docker
  args: ['push','${_IMAGE}']

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args: [
    'run','deploy','${_SERVICE}',
    '--image','${_IMAGE}',
    '--region','${_REGION}',
    '--platform','managed',
    '--allow-unauthenticated',
    '--service-account','rcv-api-sa@${PROJECT_ID}.iam.gserviceaccount.com',
    '--set-env-vars','${_ENVVARS}',
    '--set-secrets','${_SECRETS}',
    '--vpc-connector','${_CONNECTOR}',
    '--vpc-egress','private-ranges-only',
    '--min-instances','1',
    '--max-instances','50',
    '--concurrency','80',
    '--cpu','1',
    '--memory','512Mi',
    '--timeout','60'
  ]

images:
- '${_IMAGE}'
