name: Deploy
on: { push: { branches: [main] } }
permissions: { contents: read, id-token: write }
jobs:
  d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/571719403185/locations/global/workloadIdentityPools/github-pool/providers/github-rcv
          service_account: rcv-deployer-sa@rcvprod.iam.gserviceaccount.com
          create_credentials_file: true
      - uses: google-github-actions/setup-gcloud@v2
      - name: Debug auth
        run: |
          gcloud --version
          gcloud auth list
          gcloud config list
      - id: build
        name: Build
        env:
          CLOUDSDK_CORE_DISABLE_PROMPTS: "1"
        run: |
          set -e
          gcloud config set project rcvprod
          IMG="us-central1-docker.pkg.dev/rcvprod/rcv-api/rcv-api:${GITHUB_SHA}"
          gcloud builds submit backend --tag "$IMG" --timeout=1200s
          echo "image=$IMG" >> "$GITHUB_OUTPUT"
      - name: Deploy
        env:
          CLOUDSDK_CORE_DISABLE_PROMPTS: "1"
        run: |
          set -e
          gcloud run deploy rcv-api --project rcvprod --region us-central1 \
            --image "${{ steps.build.outputs.image }}" \
            --service-account rcv-api-sa@rcvprod.iam.gserviceaccount.com \
            --quiet
      - name: Verify
        run: |
          set -e
          ACTUAL=$(gcloud run services describe rcv-api --project rcvprod --region us-central1 \
            --format="value(spec.template.spec.containers[0].image)")
          echo "Actual: $ACTUAL"
          test "$ACTUAL" = "${{ steps.build.outputs.image }}"
