name: Deploy to Cloud Run
on: { push: { branches: [ "main" ] } }
permissions: { contents: read, id-token: write }
env:
  PROJECT_ID: rcvprod
  REGION: us-central1
  AR_REPO: rcv-api
  SERVICE: rcv-api
  WORKLOAD_IDENTITY_PROVIDER: projects/571719403185/locations/global/workloadIdentityPools/github-pool/providers/github-rcv
  DEPLOY_SA: rcv-deployer-sa@rcvprod.iam.gserviceaccount.com
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.DEPLOY_SA }}
        create_credentials_file: true
    - run: echo "CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=$GOOGLE_APPLICATION_CREDENTIALS" >> $GITHUB_ENV
    - uses: google-github-actions/setup-gcloud@v2
    - run: gcloud info && gcloud auth list && gcloud config get-value project
    - run: gcloud info && gcloud auth list && echo "ADC=$GOOGLE_APPLICATION_CREDENTIALS"
    - run: gcloud config set project ${{ env.PROJECT_ID }}
    - run: gcloud auth application-default print-access-token >/dev/null && echo "ADC OK"
    - run: IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/rcv-api:${{ github.sha }}"; gcloud builds submit --project=${{ env.PROJECT_ID }} --verbosity=debug backend --tag "$IMAGE" --timeout=1200s --quiet
    - run: IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.AR_REPO }}/rcv-api:${{ github.sha }}"; gcloud run deploy --project=${{ env.PROJECT_ID }} --verbosity=debug "${{ env.SERVICE }}" --region="${{ env.REGION }}" --image="$IMAGE" --quiet
