name: Deploy
on: { push: { branches: [main] } }
permissions: { contents: read, id-token: write }
jobs:
  d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/571719403185/locations/global/workloadIdentityPools/github-pool/providers/github-rcv
          service_account: rcv-deployer-sa@rcvprod.iam.gserviceaccount.com
          create_credentials_file: true
      - uses: google-github-actions/setup-gcloud@v2
      - id: build
        name: Build
        env:
          CLOUDSDK_CORE_DISABLE_PROMPTS: "1"
        run: |
          set -euo pipefail
          gcloud config set project rcvprod
          IMAGE="us-central1-docker.pkg.dev/rcvprod/rcv-api/rcv-api:${GITHUB_SHA}"
          gcloud builds submit backend --tag "$IMAGE" --timeout=1200s --verbosity=debug
          echo "image=$IMAGE" >> "$GITHUB_OUTPUT"
      - name: Deploy
        env:
          CLOUDSDK_CORE_DISABLE_PROMPTS: "1"
        run: |
          set -euo pipefail
          gcloud run deploy rcv-api --project rcvprod --region us-central1 \
            --image "${{ steps.build.outputs.image }}" \
            --service-account rcv-api-sa@rcvprod.iam.gserviceaccount.com \
            --quiet --verbosity=debug
          # sanity check: imprime la imagen efectiva
          gcloud run services describe rcv-api --project rcvprod --region us-central1 \
            --format="value(spec.template.spec.containers[0].image)"
      - name: Debug auth
        run: |
          set -x
          gcloud --version
          gcloud info
          gcloud auth list
          gcloud config list
