name: Deploy
on: { push: { branches: [main] } }
permissions: { contents: read, id-token: write }

jobs:
  d:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/571719403185/locations/global/workloadIdentityPools/github-pool/providers/github-rcv
          service_account: rcv-deployer-sa@rcvprod.iam.gserviceaccount.com
          create_credentials_file: true

      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud info && gcloud auth list && gcloud config set project rcvprod
      - name: Build
        run: |
          IMAGE="us-central1-docker.pkg.dev/rcvprod/rcv-api/rcv-api:${{ github.sha }}"
          gcloud builds submit backend --tag "$IMAGE" --timeout=1200s --verbosity=debug
      - name: Deploy
        run: |
          IMAGE="us-central1-docker.pkg.dev/rcvprod/rcv-api/rcv-api:${{ github.sha }}"
          gcloud run deploy rcv-api --region us-central1 --image "$IMAGE" \
            --service-account "rcv-api-sa@rcvprod.iam.gserviceaccount.com" --verbosity=debug
