name: Deploy
on: { push: { branches: [main] } }
permissions: { contents: read, id-token: write }
env:
  PROJECT_ID: rcvprod
  REGION: us-central1
  AR: rcv-api
  SVC: rcv-api
  WIP: projects/571719403185/locations/global/workloadIdentityPools/github-pool/providers/github-rcv
  DEPLOY_SA: rcv-deployer-sa@rcvprod.iam.gserviceaccount.com
jobs:
  d:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.WIP }}
        service_account: ${{ env.DEPLOY_SA }}
        create_credentials_file: true
    - uses: google-github-actions/setup-gcloud@v2
    - run: gcloud config set project ${{ env.PROJECT_ID }}
    - run: |
        REG=${{ env.REGION }}; PROJ=${{ env.PROJECT_ID }}; REPO=${{ env.AR }}
        IMG="$REG-docker.pkg.dev/$PROJ/$REPO/rcv-api:${{ github.sha }}"
         gcloud builds submit backend --tag "$IMG" --timeout=1200s
        gcloud run deploy "${{ env.SVC }}" --region "$REG" --image "$IMG" --service-account "rcv-api-sa@$PROJ.iam.gserviceaccount.com"
